"""Reviewed Korean meme propagation accounts."""

from .actor_catalog_types import EXACT_POST_REVIEW, KOL, actor
from .actors import ActorTier as T


KOREA_ACTORS = (
    actor(
        "yeonwoo1102", "1444971805618302988", "Yeon",
        "Korean cross-chain degen documenting Robinhood Chain and BSC meme entries",
        T.PROPAGATION_KOL, ("solana", "bsc", "robinhood", "global"), KOL,
        languages=("ko", "en"), regions=("korea",),
        telegram_public=("Yndegen",), aliases=("yeon", "yeonwoo"),
        priority=4, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/yeonwoo1102/status/2086876192154800248",),
        risks=("self-reported entries are clues, not independently verified performance",),
    ),
    actor(
        "2442lll", "1470636843905740804", "Chit",
        "Korean Binance/BSC meme propagation account tracking public hint narratives",
        T.PROPAGATION_KOL, ("bsc", "bnb", "solana", "global"), KOL,
        languages=("ko", "en"), regions=("korea",), aliases=("chit",),
        priority=5, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/2442lll/status/2086442901987533260",),
    ),
    actor(
        "ddakbbam1", "888068616", "딱밤",
        "Korean crypto shitposter and fast meme propagation account",
        T.PROPAGATION_KOL, ("solana", "bsc", "global"), KOL,
        languages=("ko", "en"), regions=("korea",), aliases=("ddakbbam",),
        priority=7, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/ddakbbam1/status/2086619815473778886",),
        risks=("Kaito Inner Circle affiliation; treat as propagation, not independent proof",),
    ),
    actor("25er__", "1855631537557131264", "25er", "Korean crypto community account", T.PROPAGATION_KOL, ("solana", "ethereum"), KOL, languages=("ko", "en"), regions=("korea",), aliases=("25er",), priority=7),
    actor("Pote_korea", "1906923828850368512", "Pote", "Korean scenario trader and commentator", T.PROPAGATION_KOL, ("solana", "ethereum", "bsc"), KOL, languages=("ko",), regions=("korea",), telegram_public=("pote_korea",), priority=7),
    actor(
        "ezeroho8245", "943399593789702144", "Leo Master",
        "Korean meme and Robinhood/BSC propagation account",
        T.PROPAGATION_KOL, ("bsc", "robinhood", "solana"), KOL,
        languages=("ko", "en"), regions=("korea",),
        telegram_realtime=("LeoMaster_memes",), priority=6,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/ezeroho8245/status/2086822309898473980",),
        risks=("profile markets influencer activity; promotion and conflict risk",),
    ),
    actor(
        "co_cobling", "1376901271790096390", "Cobling",
        "Korean BSC, RWA, and meme propagation account",
        T.PROPAGATION_KOL, ("bsc", "bnb", "rwa"), KOL,
        languages=("ko", "en"), regions=("korea",), priority=8,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/co_cobling/status/2084114816856478177",),
        risks=("has disclosed advertising; treat all calls as conflicted clues",),
    ),
    actor(
        "doodlely213", "1610618555334266881", "Doodlely",
        "Korean Solana/Base meme propagation account",
        T.PROPAGATION_KOL, ("solana", "base", "ethereum"), KOL,
        languages=("ko", "en"), regions=("korea",), priority=8,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/doodlely213/status/2083810674661273775",),
        risks=("trade commentary is self-reported and not performance evidence",),
    ),
    actor(
        "AGeullo", "1473478128026931201", "산할",
        "Korean Robinhood meme narrative ranker separating origins, authorities, and derivatives",
        T.PROPAGATION_KOL, ("robinhood", "bsc", "solana"), KOL,
        languages=("ko", "en"), regions=("korea",), priority=5,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/AGeullo/status/2075840663254655222",),
        risks=("profile invites collaborations; commercial conflicts require review",),
    ),
    actor(
        "0xblackluke", "1881598336425398272", "루크",
        "Korean Robinhood onchain-risk analyst covering snipers, bots, whales, and holders",
        T.PROPAGATION_KOL, ("robinhood", "bsc", "onchain"), KOL,
        languages=("ko", "en"), regions=("korea",), priority=6,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/0xblackluke/status/2080823056810016806",),
        risks=("ambassador and referral affiliations can bias platform mentions",),
    ),
    actor(
        "CYaChoCho", "1973511013141192710", "CYaChoCho",
        "Korean Robinhood meme, NFT, and tokenized-RWA mechanism explainer",
        T.PROPAGATION_KOL, ("robinhood", "rwa", "nft"), KOL,
        languages=("ko", "en"), regions=("korea",), priority=9,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/CYaChoCho/status/2086667129391390874",),
        risks=("small account; use mechanism analysis only after source verification",),
    ),
    actor(
        "CENTWT", "945049333262532613", "CEN",
        "Korean Robinhood low-cap and utility narrative propagation account",
        T.PROPAGATION_KOL, ("robinhood", "bsc", "solana"), KOL,
        languages=("ko", "en"), regions=("korea",),
        telegram_public=("emperorcoin",), priority=7,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/CENTWT/status/2077647640154775957",),
        risks=("profile markets influencer activity; promotion conflict is material",),
    ),
    actor(
        "ilpyung98", "2006660385416556548", "일평",
        "Korean market-traffic commentator spanning TUT, Robinhood, BSC, and Solana",
        T.PROPAGATION_KOL, ("bsc", "robinhood", "solana"), KOL,
        languages=("ko",), regions=("korea",), priority=10,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/ilpyung98/status/2086584155983491117",),
        risks=("young account and credentials or performance are self-reported",),
    ),
)
