"""BSC propagation accounts promoted from exact-CA historical audits."""

from .actor_catalog_types import EXACT_POST_REVIEW, KOL, WALLET_BINDING_REVIEW, actor
from .actors import ActorTier as T


BSC_AUDIT_KOL_ACTORS = (
    actor(
        "false2z", "1871782938754330624", "false3z",
        "BSC exact-CA selector who distinguished the main BOT contract from a fee-bearing competitor before the first-wave peak",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("en",), regions=("global",), priority=4,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/false2z/status/2086541464171860432",),
        risks=(
            "BOT post was 165 seconds after launch and does not prove narrative origin",
            "one reviewed token cannot establish a profitable longitudinal hit rate",
        ),
    ),
    actor(
        "sizzlezzzzzzzzz", "1451953767134515209", "sizzlez",
        "BSC narrative watcher who published the main BOT CA before its second catalyst wave",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("en",), regions=("global",), priority=4,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/sizzlezzzzzzzzz/status/2086945202246160555",),
        risks=(
            "the BOT post followed the initial 517x wave and cannot claim first discovery",
            "anticipated catalyst language remains a thesis until authority evidence arrives",
        ),
    ),
    actor(
        "9999btcname", "1825447165868826624", "不二和尚",
        "Chinese BSC position amplifier observed before the recorded BOT first-wave peak",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), priority=8,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/9999btcname/status/2086543875393593486",),
        risks=(
            "BOT post was 740 seconds after launch and may reflect an existing move",
            "position language is not proof of source status, wallet ownership, or causation",
        ),
    ),
    actor(
        "99X_FJTL", "1515321304777629697", "他们都叫我水哥",
        "Chinese BSC community operator and meme propagation account",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), aliases=("水哥",),
        priority=4, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/99X_FJTL/status/2060676250897916297",),
        risks=(
            "profile discloses paid KOL promotion and exchange referrals",
            "wallet timing is research evidence, never contract authority",
        ),
    ),
    actor(
        "52Hz_eth", "1872719104416858115", "52Hz.eth🦄",
        "Chinese BSC meme channel operator and narrative commentator",
        T.PROPAGATION_KOL, ("bsc", "bnb", "ethereum"), KOL,
        languages=("zh",), regions=("china",), aliases=("52Hz",),
        priority=4, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/52Hz_eth/status/2082780087515304051",),
        risks=(
            "later performance recaps must not be treated as first calls",
            "multi-token posts require exact-CA attribution per token",
        ),
    ),
    actor(
        "meligamble", "333762244", "wake up or keep dreaming?",
        "Low-cap secondary X account directly disclosed by meliboi_sama",
        T.PROPAGATION_KOL, ("bsc", "solana", "global"), KOL,
        languages=("en", "zh"), regions=("global",), aliases=("meli gamble",),
        priority=5, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/meligamble/status/2057855535513501856",),
        risks=("position post has no exact public wallet attribution",),
    ),
    actor(
        "meliboi_sama", "1639851624431767553", "meliboi sama",
        "Meme narrative commentator with a directly linked low-cap X account",
        T.PROPAGATION_KOL, ("bsc", "solana", "global"), KOL,
        languages=("en",), regions=("global",), aliases=("meliboi",),
        priority=5, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/meliboi_sama/status/2082792674902655205",),
        risks=("builder and ambassador affiliations create commercial conflicts",),
    ),
    actor(
        "ZephyrTrading", "1755186363085783040", "Zephyr",
        "Chinese cross-chain degen diary and alpha-channel operator",
        T.PROPAGATION_KOL, ("bsc", "solana", "ethereum"), KOL,
        languages=("zh",), regions=("china",), aliases=("Zephyr",),
        priority=6, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/ZephyrTrading/status/2074606340471976359",),
        risks=("channel promotion and position bias require independent chronology",),
    ),
    actor(
        "SuperL9", "594717639", "SuperL9",
        "Chinese BSC meme-cycle and narrative propagation account",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), priority=6,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/SuperL9/status/2073734939267461248",),
        risks=("audited examples were already multi-million market context",),
    ),
    actor(
        "0x__117", "1909173490630225920", "117",
        "Chinese BSC exact-CA commentator and position diarist",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), aliases=("117",),
        priority=5, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/0x__117/status/2069690773675843603",),
        risks=("community-token positions can bias comparative theses",),
    ),
    actor(
        "0xNra1", "2073040424412082176", "Nra",
        "BSC on-chain trader publishing exact-CA price theses",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("en", "zh"), regions=("asia",), priority=6,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/0xNra1/status/2083553643547222267",),
        risks=("public post contains no exact wallet attribution",),
    ),
    actor(
        "DaLai77988", "1137771059833446401", "大来+🔶BNB",
        "Chinese BSC community trader publishing position and valuation views",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), aliases=("大来",),
        priority=6, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/DaLai77988/status/2065238495702982770",),
        risks=("community and business contacts create promotion conflicts",),
    ),
    actor(
        "jiaodu6688", "2034634079153606656", "今晚打老虎🐯",
        "Self-disclosed secondary X account publishing BSC exact-CA theses",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), aliases=("今晚打老虎",),
        priority=5, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/jiaodu6688/status/2083225512591573478",),
        risks=("suspended main account is disclosed but its handle is not named",),
    ),
    actor(
        "moneymancalls", "1355151884248621056", "investor",
        "BNB supporter publishing position and catalyst theses",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("en",), regions=("global",), priority=6,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/moneymancalls/status/2085695771261739426",),
        risks=("self-reported position is not an independently bound wallet buy",),
    ),
    actor(
        "PredictedWAXX", "1600931469874061312", "Waxx",
        "Liquidity provider publishing BSC and Robinhood coin analysis",
        T.PROPAGATION_KOL, ("bsc", "robinhood"), KOL,
        languages=("en",), regions=("global",), aliases=("Waxx",),
        priority=6, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/PredictedWAXX/status/2082879470541971962",),
        risks=("multi-contract watchlists need per-CA semantic attribution",),
    ),
    actor(
        "treyerl", "574166659", "treyerl💎",
        "Meme-news account publishing valuation and narrative theses",
        T.PROPAGATION_KOL, ("bsc", "global"), KOL,
        languages=("en",), regions=("global",), priority=6,
        basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/treyerl/status/2082793042193666326",),
        risks=(
            "profile affiliation with meliboi_sama is one-way and not same-person proof",
        ),
    ),
    actor(
        "ts65855", "1884707335454810112", "二三",
        "Chinese early-value account publishing exact-CA position claims",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), aliases=("二三",),
        priority=6, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/ts65855/status/2074161865102688652",),
        risks=("claimed position size has no exact public wallet attribution",),
    ),
    actor(
        "yig168168", "1908874937861120001", "币圈壹哥",
        "Chinese trading and community account publishing direct entry prompts",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), aliases=("币圈壹哥",),
        priority=6, basis=EXACT_POST_REVIEW,
        evidence=("https://x.com/yig168168/status/2064955544411275680",),
        risks=("community-building and promotion incentives require discounting",),
    ),
    actor(
        "mstzera", "1047951613934100484", "mstzera",
        "Provider-bound BSC wallet account observed in early BOT and CLIPPY buys",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("en", "pt"), regions=("global",), priority=5,
        basis=WALLET_BINDING_REVIEW,
        evidence=(
            "https://gmgn.ai/bsc/token/0xbcad9b1b85af1cd81437252bf50b87235c0b7777",
            "https://bscscan.com/tx/0x338b9629989277b9ea547c588bb02975b5b5d8f66cb3ab6733bac5c1cfffcf1f",
        ),
        risks=(
            "only two eligible tokens were retained, so the outcome denominator is incomplete",
            "provider wallet binding is not proof that public posts caused either move",
        ),
    ),
    actor(
        "Stigman__", "1272354183677644800", "Stigman",
        "Provider-bound BSC wallet account observed 69 seconds into BOT launch",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("en",), regions=("global",), priority=5,
        basis=WALLET_BINDING_REVIEW,
        evidence=(
            "https://gmgn.ai/bsc/token/0xbcad9b1b85af1cd81437252bf50b87235c0b7777",
            "https://bscscan.com/tx/0xba2343e8cf04c1b1addf352af2333930a433eb937179485c04d1fed7969d4203",
        ),
        risks=(
            "ten eligible tokens and five pre-peak tokens do not form a complete outcome denominator",
            "provider wallet binding is not proof of narrative origin or public influence",
        ),
    ),
    actor(
        "rawrstarxdd", "1928506739915419648", "rawrstarxdd",
        "Provider-bound BSC wallet account with two BOT buys before the first peak",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("en",), regions=("global",), priority=6,
        basis=WALLET_BINDING_REVIEW,
        evidence=(
            "https://gmgn.ai/bsc/token/0xbcad9b1b85af1cd81437252bf50b87235c0b7777",
            "https://bscscan.com/tx/0xc39b502578dcb00f6409f44a92db0ab0ec37c7c311ff046ea54608c308d630c4",
        ),
        risks=(
            "five retained eligible tokens all preceded their local peaks, but outcomes remain incomplete",
            "two BOT transactions are one launch episode rather than independent wins",
        ),
    ),
    actor(
        "0xfanfanfan", "1862446599378743296", "凡",
        "Provider-bound Chinese BSC wallet account observed before the BOT first-wave peak",
        T.PROPAGATION_KOL, ("bsc", "bnb"), KOL,
        languages=("zh",), regions=("china",), priority=7,
        basis=WALLET_BINDING_REVIEW,
        evidence=(
            "https://gmgn.ai/bsc/token/0xbcad9b1b85af1cd81437252bf50b87235c0b7777",
            "https://bscscan.com/tx/0xab152a3364dc0e7889cd8df254c955e48cece2405a07dd7d8a0819e70980e20f",
        ),
        risks=(
            "only four eligible tokens and two pre-peak tokens were retained",
            "no reviewed pre-peak exact-CA post establishes public discovery or causation",
        ),
    ),
)
