"""Self-contained read-only dashboard page."""

DASHBOARD_HTML = r"""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DeBot · 叙事雷达</title><style>
:root{color-scheme:dark;--bg:#071017;--panel:#0d1922;--panel2:#102330;--line:#203746;--text:#eaf6ff;--muted:#86a0b2;--green:#42d6a4;--amber:#f5c66a;--red:#ff7b7b;--blue:#65b7ff}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% -20%,#17384a 0,transparent 42%),var(--bg);color:var(--text);font:14px Inter,ui-sans-serif,system-ui,sans-serif}main{max-width:1500px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-end}h1{font-size:25px;margin:0 0 5px;letter-spacing:.2px}.muted{color:var(--muted)}.badge{display:inline-flex;border:1px solid var(--line);border-radius:999px;padding:5px 9px;background:#0a151d}.notice{margin:18px 0;padding:11px 14px;border:1px solid #594b25;background:#211d10;border-radius:9px;color:var(--amber)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.card{background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:11px;padding:13px;min-height:80px}.value{font-size:23px;font-weight:760;margin-top:7px}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}h2{font-size:17px;margin:26px 0 10px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:10px}input,select{background:#0a141c;color:var(--text);border:1px solid var(--line);border-radius:8px;padding:9px 11px;outline:none}input{min-width:290px;flex:1}.tablebox{overflow:auto;border:1px solid var(--line);border-radius:11px;background:var(--panel)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 11px;border-bottom:1px solid var(--line);vertical-align:top}th{position:sticky;top:0;background:#0c1821;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.5px;z-index:1}td{min-width:105px}td.wide{min-width:250px;white-space:normal}.account{font-weight:700}.sub{font-size:12px;color:var(--muted);margin-top:3px;max-width:360px}.tags{display:flex;flex-wrap:wrap;gap:4px}.tag{font-size:11px;padding:2px 6px;border:1px solid var(--line);border-radius:999px;color:#bfd2df;background:#0b1720}a{color:var(--blue);text-decoration:none}a:hover{text-decoration:underline}.empty{padding:22px;color:var(--muted)}.dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--green);margin-right:6px}.dot.off{background:var(--red)}@media(max-width:700px){main{padding:12px}header{display:block}.badge{margin-top:10px}input{min-width:100%}}
</style></head><body><main><header><div><h1>DeBot · 叙事研究状态</h1><div class="muted" id="stamp">读取运行状态…</div></div><div class="badge" id="runtime">服务状态未知</div></header>
<div class="notice">研究模式：展示采集、取证和 exact-CA 绑定结果；当前不授权交易，盈利能力仍需实盘样本验证。</div>
<div class="grid" id="cards"></div>
<h2>数据源</h2><div class="grid" id="sources"></div>
<h2>15 秒 推文→Mint 报警</h2><div class="sub">监控 X 帖子触发；仅当 DeBot new / completing / completed 候选精确绑定同一帖子并通过门禁，才报警具体 CA。裸 mint、RPC 和模型均不触发报警。</div><div class="tablebox" id="mintAlerts"></div>
<h2>X 实时互动测试</h2><div class="sub" id="repostNote">转发探针初始化中；点赞不在 FxTwitter 公共时间线中。</div><div class="tablebox" id="reposts"></div>
<h2>监控人物与 KOL</h2><div class="toolbar"><input id="search" placeholder="搜索账号、姓名、身份、地区、链…"><select id="ecosystem"><option value="">全部生态</option></select><span class="badge" id="shown"></span></div><div class="tablebox" id="actors"></div>
<h2>最近叙事研究</h2><div class="tablebox" id="research"></div>
</main><script>
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tags=v=>(v||[]).map(x=>'<span class="tag">'+e(x)+'</span>').join('')||'<span class="muted">—</span>';
const link=(url,label)=>/^https:\/\//.test(url||'')?'<a href="'+e(url)+'" target="_blank" rel="noreferrer">'+e(label)+'</a>':e(label);
const table=(rows,cols)=>rows.length?'<table><thead><tr>'+cols.map(c=>'<th>'+e(c[0])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td class="'+(c[2]||'')+'">'+c[1](r)+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'<div class="empty">暂无数据</div>';
let state={actors:[]};
function card(name,value,tone=''){return '<div class="card"><div class="muted">'+e(name)+'</div><div class="value '+tone+'">'+e(value)+'</div></div>'}
function renderSources(s){let names={x:'X / FxTwitter',telegram:'Telegram',debot:'DeBot 私有信号',market:'BSC 1h 异动',bsc_mints:'BSC RPC 审计'};document.querySelector('#sources').innerHTML=Object.entries(s.sources||{}).map(([k,v])=>{let count=k==='x'?v.checkpointed_accounts:k==='telegram'?v.checkpointed_channels:k==='debot'?v.seen_signals:k==='bsc_mints'?v.last_processed_block:v.emitted_anomalies;return '<div class="card"><div><span class="dot '+(v.available?'':'off')+'"></span>'+e(names[k]||k)+'</div><div class="value">'+e(count??0)+'</div><div class="sub">checkpoint '+e(v.updated_at||'尚未建立')+'</div></div>'}).join('')}
function renderMintAlerts(s){let a=s.mint_alerts||{},rows=a.recent_alerts||[];document.querySelector('#mintAlerts').innerHTML=table(rows,[['报警时间',r=>e(r.raised_at)+'<div class="sub">推文 '+e(r.catalyst_created_at)+'</div>'],['Token / CA',r=>'<div class="account">'+e(r.token_symbol||r.token_name||'未命名')+'</div><div class="sub">'+e(r.exact_ca)+'</div>','wide'],['精确绑定',r=>link(r.catalyst_status_url,'@'+r.catalyst_author)+'<div class="sub">DeBot '+e(r.token_stage)+'</div>'],['延迟',r=>'<div class="'+(r.within_detection_sla?'ok':'bad')+'">发现 '+e(Number(r.detection_latency_seconds||0).toFixed(3))+'s</div><div class="sub">投递 '+e(r.delivery_latency_seconds==null?'待投递':Number(r.delivery_latency_seconds).toFixed(3)+'s')+'</div>'],['投递',r=>'<div class="'+(r.delivery_status==='delivered'?'ok':'warn')+'">'+e(r.delivery_status)+'</div><div class="sub">尝试 '+e(r.delivery_attempts||0)+' 次</div>']])}
function renderReposts(rt){let p=rt.x_reposts||{},rows=p.recent_events||[],poll=Object.values(p.target_poll_seconds||{})[0]??'—';document.querySelector('#repostNote').textContent='已初始化 '+(p.initialized_targets||0)+' / '+(p.configured_targets||0)+' 个账号 · '+poll+'s 轮询 · 记录系统首次看到时间，不伪造 X 点击时间 · 点赞不可见 · 不进入交易队列';document.querySelector('#reposts').innerHTML=table(rows,[['发现时间',r=>e(r.detected_at)],['账号 / 动作',r=>'<div class="account">@'+e(r.reposter)+'</div><div class="sub">转发 · 测试专用</div>'],['原帖',r=>link(r.source_url,'@'+r.original_author+' / '+r.original_tweet_id)+'<div class="sub">原帖时间 '+e(r.original_created_at)+'</div>'],['内容',r=>e(r.text),'wide']])}
function renderActors(){let q=document.querySelector('#search').value.trim().toLowerCase(),eco=document.querySelector('#ecosystem').value;let rows=(state.actors||[]).filter(a=>{let hay=[a.handle,a.display_name,a.role,...(a.ecosystems||[]),...(a.regions||[]),...(a.languages||[])].join(' ').toLowerCase();return (!q||hay.includes(q))&&(!eco||(a.ecosystems||[]).includes(eco))});document.querySelector('#shown').textContent='显示 '+rows.length+' / '+(state.actors||[]).length;document.querySelector('#actors').innerHTML=table(rows,[['账号',a=>'<div class="account">'+link('https://x.com/'+a.handle,'@'+a.handle)+'</div><div class="sub">'+e(a.display_name)+'</div>'],['身份',a=>'<div>'+e(a.role)+'</div><div class="sub">ID '+e(a.author_id)+'</div>','wide'],['生态 / 地区',a=>'<div class="tags">'+tags(a.ecosystems)+'</div><div class="sub">'+e((a.regions||[]).join(' · '))+' · '+e((a.languages||[]).join('/'))+'</div>','wide'],['权限边界',a=>'<div class="tags">'+tags(a.capabilities)+'</div><div class="sub">'+e(a.tier)+'</div>','wide'],['采集',a=>'<div><span class="dot '+(a.checkpointed?'':'off')+'"></span>'+(a.monitor_x?'X '+e(a.poll_seconds)+'s':'X 关闭')+(a.monitor_reposts?' · 转发探针 1s':'')+'</div><div class="sub">'+(a.latest_status_url?link(a.latest_status_url,'最近 checkpoint'):'尚无最新帖')+(a.telegram_channels?.length?' · TG '+e(a.telegram_channels.join(', ')):'')+'</div>','wide']])}
function renderResearch(rows){document.querySelector('#research').innerHTML=table(rows||[],[['时间',r=>e(r.researched_at)],['触发',r=>(r.source_url?link(r.source_url,r.subject||r.mode):e(r.subject||r.mode))+'<div class="sub">'+e(r.exact_ca||r.trigger_id)+'</div>'],['叙事',r=>'<div class="account">'+e(r.quality==='invalid_template_echo'?'历史结果无效：模板回显':(r.narrative_key||'尚未形成有效叙事'))+'</div><div>'+e(r.one_line_meme||'')+'</div><div class="sub">'+e(r.why_now||'')+'</div>','wide'],['结果',r=>'<div class="'+(r.status==='READY'||r.status==='EVIDENCE_FOUND'?'ok':'warn')+'">'+e(r.status)+'</div><div class="sub">'+e(r.reason)+(r.quality==='invalid_template_echo'?' · 已由新门禁拦截':'')+'</div>','wide'],['证据',r=>(r.verified_urls||[]).map((u,i)=>link(u,'原帖 '+(i+1))).join('<br>')||'<span class="muted">无已核验 URL</span>']])}
function render(s){state=s;let j=s.jobs||{},q=j.counts||{},r=s.research||{},a=s.mint_alerts||{},rt=s.runtime||{},rp=rt.x_reposts||{};document.querySelector('#stamp').textContent='状态生成 '+(s.generated_at||'—')+' · 页面每 2 秒刷新';document.querySelector('#runtime').innerHTML='<span class="dot '+(rt.running?'':'off')+'"></span>'+(rt.running?'采集与研究服务运行中':'仅看板 / 服务状态未知');document.querySelector('#cards').innerHTML=[card('监控人物',s.actor_count||0),card('推文→Mint 报警',a.total||0),card('待投递报警',a.pending_delivery||0,(a.pending_delivery||0)?'warn':''),card('15s 内发现',a.detection_sla_met||0,'ok'),card('待研究',q.pending||0,(q.pending||0)?'warn':''),card('研究中',q.leased||0),card('已完成任务',q.done||0,'ok'),card('失败任务',q.failed||0,(q.failed||0)?'bad':''),card('研究包',r.total||0),card('转发探针事件',rp.total_events||0),card('DeBot 三阶段轮询',(s.polling?.mint_seconds??'—')+'s/阶段'),card('BSC RPC 审计',s.polling?.chain_mint_seconds==null?'关闭':s.polling.chain_mint_seconds+'s')].join('');renderSources(s);renderMintAlerts(s);renderReposts(rt);let ecosystems=[...new Set((s.actors||[]).flatMap(a=>a.ecosystems||[]))].sort();let select=document.querySelector('#ecosystem'),chosen=select.value;select.innerHTML='<option value="">全部生态</option>'+ecosystems.map(x=>'<option value="'+e(x)+'">'+e(x)+'</option>').join('');select.value=chosen;renderActors();renderResearch(r.recent_packages||[])}
document.querySelector('#search').addEventListener('input',renderActors);document.querySelector('#ecosystem').addEventListener('change',renderActors);
async function tick(){try{let q=await fetch('/api/status',{cache:'no-store'});if(!q.ok)throw Error(q.status);render(await q.json())}catch(err){document.querySelector('#stamp').textContent='状态读取失败: '+err}finally{setTimeout(tick,2000)}}tick();
</script></body></html>""".encode("utf-8")
